Add clang fixes (#9)
* fix warning Wno-undefined-optimized

* fix undefined reference to 'stpcpy'

* disable CONFIG_CRYPTO_FIPS

* Fix GCC_TOOLCHAIN_DIR prefix for Clang cross compilation

* cert host tools: Stop complaining about deprecated OpenSSL functions

* Nuke mstdrv

* fix  warning: equality comparison with extraneous parentheses [-Wparentheses-equality]

* build: fix clang support
The kernel compiles with clang, but doesn't boot because of memory
unalignment. To fix this, force all objects to be aligned.

* Disable warning as error for strict-prototypes (fix build with clang 20)